### DISCUSSION TITLE
v9 Testing Discussion

### DISCUSSION THREAD

**Discussion by czarcas7ic** [osmosis-labs/osmosis#1543] [General]
A list of things we want to test for the v9 upgrade:

- [ ] Token factory
  - [ ] Test token creation  
- [x] GAMM
  - [x] Create 60/40 pool on v8 and a 60/40 pool on v9
    - [x] Swap / LP actions, check amount out and supply afterwards, numbers between v8 and v9 should be very close
  - [x] Create 50/50 pool on v8 and a 50/50 pool on v9
    - [x] Swap / LP actions, check amount out and supply afterwards, numbers between v8 and v9 should be very close
- [x] Superfluid
   - [x] Check that superfluid delegators get votes / properly override their validators vote
- [x] Bank
   - [x] Send txfee in non-osmo asset
     - [x] See if coin gets swapped at epoch
     - [x] Ensure swap fee goes to stakers

**Comment by ValarDragon** [comment]
We also need to test sending a txfee in a non-osmo asset, and whether that manifests in that coin getting swapped at epoch and going to stakers

**Comment by czarcas7ic** [comment]
- [x] Bank
   - [x] Send txfee in non-osmo asset
     - [x] See if coin gets swapped at epoch
     - [x] Ensure swap fee goes to stakers


## Test osmo tx fee
val osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a
val osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
test1 osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks

Stake test1 to val

`osmosisd tx staking delegate osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 500000000uosmo --from test1 -b block --keyring-backend test`

9644900162BDAF85059442F945367516BC98BFF9A9EF9DBC6849638BAEB275AF

Send a regular tx from val to test2 with 5000000uosmo fees

`osmosisd tx bank send val osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv 1000000uosmo --from val -b block --keyring-backend test --fees 5000000uosmo`
9D47E9430B95577F3B8A39E4E02DD4C7F06737BCA3B0A3A729E832BA0C9E7C5F
Height 20

Check test1 rewards pre epoch and pre tx send(epoch 2 started block 13)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 19`
```
rewards: []
```

Check test1 rewards pre epoch and post tx send(epoch 2 started block 13)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 21`
```
rewards:
- amount: "2205000.000000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and pre tx send(epoch 2 started block 13)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 19`

```
rewards:
- amount: "1764000.000000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and post tx send(epoch 2 started block 13)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 21`
```
rewards:
- amount: "3969000.000000000000000000"
  denom: uosmo
```


test1 rewards from fees: 2205000
val rewards from fees: 2205000
Total: 4410000
Missing: 590000


## Test osmo tx fee (test 2 due to missing amount)
Send a regular tx from test2 to test3 with 5000000uosmo fees

`osmosisd tx bank send test2 osmo1qwexv7c6sm95lwhzn9027vyu2ccneaqad4w8ka 1000000uosmo --from test2 -b block --keyring-backend test --fees 5000000uosmo`
980C7BB85EE57E3028291420453C870B6F7DFD58E81A2441C9135ED526948339
Height 793

Check test1 rewards pre epoch and pre tx send(epoch 67 started block 787)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 792`
```
rewards:
- amount: "66150000.000000000000000000"
  denom: uosmo
```

Check test1 rewards pre epoch and post tx send(epoch 67 started block 787)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 794`
```
rewards:
- amount: "68355000.000000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and pre tx send(epoch 67 started block 787)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 792`

```
rewards:
- amount: "67914000.000000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and post tx send(epoch 67 started block 787)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 794`
```
rewards:
- amount: "70119000.000000000000000000"
  denom: uosmo
```

test1 rewards from fees: 68355000-66150000=2205000
val rewards from fees: 70119000-67914000=2205000
Total: 4410000
Missing: 590000

## Test ion tx fee

Need to first create a osmo/ion pool, then add to tx fee whitelist

```json
{
    "weights": "5uion,5uosmo",
    "initial-deposit": "50000000uion,50000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test2 --pool-file pool.json -b block`
AF27BBBC1014096E820BB1B9C82DC7B7AF8CD60DAD3F97C9765FD1451B612622

`osmosisd q gamm pools`
```
pools:
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t
  future_pool_governor: ""
  id: "1"
  poolAssets:
  - token:
      amount: "50000000"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "50000000"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "100000000000000000000"
    denom: gamm/pool/1
  totalWeight: "10737418240"
```

Add to tx fee whitelist (had to fix the command since it didn't work, PR up right now https://github.com/osmosis-labs/osmosis/pull/1546)

`osmosisd tx txfees update-fee-token uion 1 --description "add uion as fee token" --title "uion fee" --from test2`
56EEDBAC36B92E75D3BFA6E56E131D2DB7439A8F7BDD2D713795DCD8E50B6E2D

Deposit
`osmosisd tx gov deposit 1 500000000uosmo --from test2 -b block`

Vote
`osmosisd tx gov vote 1 yes --from val --keyring-backend test -b block`

Check it got added
`osmosisd q txfees fee-tokens`
```
fee_tokens:
- denom: uion
  poolID: "1"
```

Send a regular tx from test2 to test3 with 5000000uion fees

`osmosisd tx bank send test2 osmo1qwexv7c6sm95lwhzn9027vyu2ccneaqad4w8ka 1000000uosmo --from test2 -b block --keyring-backend test --fees 5000000uion`
1954F5C948FE834D177293285A7208A070F1D02CCAED07A66960068932F1E145
Height 1395

Check test1 rewards pre epoch and pre tx send(epoch 118 started block 1394)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1394`
```
rewards:
- amount: "113337000.000000000000000000"
  denom: uosmo
```

Check test1 rewards pre epoch and post tx send(epoch 118 started block 1394)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1396`
```
rewards:
- amount: "113337000.000000000000000000"
  denom: uosmo
```

Check test1 rewards post next epoch and post tx send(epoch 119 started block 1406)
`osmosisd q distribution rewards osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1407`
```
rewards:
- amount: "116205305.454000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and pre tx send(epoch 118 started block 1394)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1394`

```
rewards:
- amount: "115101000.000000000000000000"
  denom: uosmo
```

Check val rewards pre epoch and post tx send(epoch 118 started block 1394)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1396`
```
rewards:
- amount: "115101000.000000000000000000"
  denom: uosmo
```

Check val rewards post next epoch and post tx send(epoch 119 started block 1406)
`osmosisd q distribution rewards osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --height 1407`
```
rewards:
- amount: "117969305.454000000000000000"
  denom: uosmo
```


test1 rewards from fees: 
epoch 116 to 117 (non fee epoch)= 112455000-111573000=882000
epoch 117 to 118 (non fee epoch)= 113337000-112455000=882000
epoch 118 to 119 (fee epoch)= 116205305-113337000=2868305

val rewards from fees: 
epoch 116 to 117 (non fee epoch)= 114219000-113337000=882000
epoch 117 to 118 (non fee epoch)= 115101000-114219000=882000
epoch 118 to 119 (fee epoch)= 117969305-115101000=2868305
post epoch with tx fees - normal rewards = 2868305-882000=1986305

5000000uion made it to pool, 4504094uosmo came out

Total: 3972610
Missing: 531484

There is only two delegators (the validator itself and the test1 account) as shown below:
```
delegation_responses:
- balance:
    amount: "500000000"
    denom: uosmo
  delegation:
    delegator_address: osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a
    shares: "500000000.000000000000000000"
    validator_address: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
- balance:
    amount: "500000000"
    denom: uosmo
  delegation:
    delegator_address: osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks
    shares: "500000000.000000000000000000"
    validator_address: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
```

**Comment by czarcas7ic** [comment]
- [x] Superfluid
   - [x] Check that superfluid delegators get votes / properly override their validators vote

## Test superfluid voting

First we have to set superfluid asset thru prop

`osmosisd tx gov submit-proposal set-superfluid-assets-proposal --superfluid-assets gamm/pool/1 --from val -b block --title "sfs" --description "gamm/pool/1" --keyring-backend test`

Deposit
`osmosisd tx gov deposit 1 500000000uosmo --from test2 -b block --keyring-backend test`

Vote
`osmosisd tx gov vote 1 yes --from val --keyring-backend test -b block --keyring-backend test`

Lock tokens for same as unbonding time

`osmosisd tx lockup lock-tokens 100000000000000000000gamm/pool/1 --from test2 -b block --duration 240s --keyring-backend test`

Lock ID from this is 1

Create SFS from this lock

`osmosisd tx superfluid delegate 1 osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --from test2 -b block --keyring-backend test`

Create a text prop
`osmosisd tx gov submit-proposal --type "Text" --title "test" --description "sfs vote test" -b block --from val --keyring-backend test`

Deposit
`osmosisd tx gov deposit 3 500000000uosmo --from test2 -b block --keyring-backend test`

Vote yes on validator
`osmosisd tx gov vote 3 yes --from val --keyring-backend test -b block`

Vote no on sfs address (only has sfs, no regular stake)
`osmosisd tx gov vote 3 no --from test2 -b block --keyring-backend test`

Show results from vote
```
final_tally_result:
  abstain: "0"
  "no": "0"
  no_with_veto: "0"
  "yes": "1022747950"
```

SFS did not overwrite validator vote

Lets look at all delegations to validator

`osmosisd q staking delegations-to osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6`

```
delegation_responses:
- balance:
    amount: "500000000"
    denom: uosmo
  delegation:
    delegator_address: osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a
    shares: "500000000.000000000000000000"
    validator_address: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
- balance:
    amount: "22747950"
    denom: uosmo
  delegation:
    delegator_address: osmo19e695wretzndjajd5rjaassya3jel4zhd4n7jt
    shares: "22747950.000000000000000000"
    validator_address: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
- balance:
    amount: "500000000"
    denom: uosmo
  delegation:
    delegator_address: osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks
    shares: "500000000.000000000000000000"
    validator_address: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
```

First address is the validator self delegation, second address should be the SFS delegation, third address is the test1 delegation

Lets figure out what that second address is from. Its the intermediary account:

`osmosisd q superfluid all-intermediary-accounts`
```
accounts:
- address: osmo19e695wretzndjajd5rjaassya3jel4zhd4n7jt
  denom: gamm/pool/1
  gauge_id: "4"
  val_addr: osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
pagination: null
```

**Comment by czarcas7ic** [comment]
- [x] Token factory
  - [x] Test token creation  

## Token Factory

Successful token creation
`osmosisd tx tokenfactory create-denom "testdenom" --from val --keyring-backend test -b block`

`osmosisd q tokenfactory denoms-from-creator osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a`
```
denoms:
- factory/osmo1phaxpevm5wecex2jyaqty2a4v02qj7qmlmzk5a/testdenom
```

Will test the rest of this module soon

**Comment by czarcas7ic** [comment]
- [x] GAMM
  - [x] Create 60/40 pool on v8 and a 60/40 pool on v9
    - [x] Swap / LP actions, check amount out and supply afterwards, numbers between v8 and v9 should be very close
  - [x] Create 50/50 pool on v8 and a 50/50 pool on v9
    - [x] Swap / LP actions, check amount out and supply afterwards, numbers between v8 and v9 should be very close

## GAMM Tests

### V9

Create a 50/50 Pool

```json
{
    "weights": "5uion,5uosmo",
    "initial-deposit": "50000000uion,50000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test2 --pool-file pool.json -b block --chain-id localosmosis`

Create a 60/40 Pool

```json
{
    "weights": "6uion,4uosmo",
    "initial-deposit": "60000000uion,40000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test3 --pool-file pool1.json -b block --chain-id localosmosis`

`osmosisd q gamm pools`

```
pools:
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t
  future_pool_governor: ""
  id: "1"
  poolAssets:
  - token:
      amount: "50000000"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "50000000"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "100000000000000000000"
    denom: gamm/pool/1
  totalWeight: "10737418240"
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wszun4a5
  future_pool_governor: ""
  id: "2"
  poolAssets:
  - token:
      amount: "60000000"
      denom: uion
    weight: "6442450944"
  - token:
      amount: "40000000"
      denom: uosmo
    weight: "4294967296"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "100000000000000000000"
    denom: gamm/pool/2
  totalWeight: "10737418240"
```

Single asset LP ION to pool1 (test7)

`osmosisd tx gamm join-swap-extern-amount-in 10000000uion 10000000 --pool-id 1 --from test7 --chain-id localosmosis -b block`
8616754579BF5C5BC24141C7356FD1E5175126CEA615FAF012E4F9AA826FD160

Single asset LP OSMO to pool1 (test8)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uosmo 10000000 --pool-id 1 --from test8 --chain-id localosmosis -b block`
0F03A5161F48A46F8FC6C1DB89356225951A2838548DD98C7EBBBE3C8C37895B


Single asset LP ION to pool2 (test9)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uion 10000000 --pool-id 2 --from test9 --chain-id localosmosis -b block`
9B08A93A709E0DEAA53A57989746C862B1DB27BCAECA75A3B2F22207CA20AF37


Single asset LP OSMO to pool2 (test10)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uosmo 10000000 --pool-id 2 --from test10 --chain-id localosmosis -b block`
F9FD6FFB2BC913572FB22BD21B91743C751AC2762CD7FD0D27C65D1A402A16FA


Exit 50 percent of initial from pool1 (test2)
`osmosisd tx gamm exit-pool --from test2 --share-amount-in 50000000000000000000 -b block --pool-id 1 --min-amounts-out=20000000uosmo,20000000uion --chain-id localosmosis`
A1EADDAD419B4452D128F796E31DE09266D72C81AD33ABC610C04DECF12C27D0


Exit 50 percent of initial from pool2 (test3)
`osmosisd tx gamm exit-pool --from test3 --share-amount-in 50000000000000000000 -b block --pool-id 2 --min-amounts-out=15000000uosmo,25000000uion --chain-id localosmosis`

F049C4BA87BBD31500E9A797E8F6D89C747B2BFD6A74647001110A399DA6197E

Query all pools again

`osmosisd q gamm pools`
```
pools:
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t
  future_pool_governor: ""
  id: "1"
  poolAssets:
  - token:
      amount: "35229358"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "35229358"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69900000000000000161"
    denom: gamm/pool/1
  totalWeight: "10737418240"
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wszun4a5
  future_pool_governor: ""
  id: "2"
  poolAssets:
  - token:
      amount: "41084635"
      denom: uion
    weight: "6442450944"
  - token:
      amount: "29346168"
      denom: uosmo
    weight: "4294967296"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69832480157406130640"
    denom: gamm/pool/2
  totalWeight: "10737418240"
```

Query balance of test1 wallet:

`osmosisd q bank balances osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks`
```
balances:
- amount: "100000000000"
  denom: uion
- amount: "10000000000"
  denom: uosmo
```

### Test a swap-exact-amount-in

Swap 5 osmo for a minimum of 4 ion

`osmosisd tx gamm swap-exact-amount-in 5000000uosmo 4000000 --swap-route-pool-ids 1 --swap-route-denoms uion --from test1 --chain-id localosmosis -b block --keyring-backend test`

`osmosisd q bank balances osmo1cyyzpxplxdzkeea7kwsydadg87357qnahakaks`
```
balances:
- amount: "100004340171"
  denom: uion
- amount: "9995000000"
  denom: uosmo
```

I received 4.3 ion when I requested of a minimum of 4 ion. It checks out.

Lastly, query the pool one more time to ensure nothing looks off:

`osmosisd q gamm pool 1`
Pre swap
```
  id: "1"
  poolAssets:
  - token:
      amount: "35229358"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "35229358"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69900000000000000161"
```
Post swap
```
  id: "1"
  poolAssets:
  - token:
      amount: "30889187"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "40229358"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69900000000000000161"
``` 

Ion increased by 4340171

Osmo decreased by -5000000

## V8

Create a 50/50 Pool

```json
{
    "weights": "5uion,5uosmo",
    "initial-deposit": "50000000uion,50000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test2 --pool-file pool.json -b block --chain-id localosmosis`
4F759B01545DC41F687C291B1B7441429482C39B4715946638A311BC918EFB1D

Create a 60/40 Pool

```json
{
    "weights": "6uion,4uosmo",
    "initial-deposit": "60000000uion,40000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test3 --pool-file pool1.json -b block --chain-id localosmosis`
6452BBBCF16B90F27616026DA2EBD112C6339841C2011C1106FDE2FE3375D760

`osmosisd q gamm pools`

```
pools:
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t
  future_pool_governor: ""
  id: "1"
  poolAssets:
  - token:
      amount: "50000000"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "50000000"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "100000000000000000000"
    denom: gamm/pool/1
  totalWeight: "10737418240"
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wszun4a5
  future_pool_governor: ""
  id: "2"
  poolAssets:
  - token:
      amount: "60000000"
      denom: uion
    weight: "6442450944"
  - token:
      amount: "40000000"
      denom: uosmo
    weight: "4294967296"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "100000000000000000000"
    denom: gamm/pool/2
  totalWeight: "10737418240"
```

Single asset LP ION to pool1 (test7)

`osmosisd tx gamm join-swap-extern-amount-in 10000000uion 10000000 --pool-id 1 --from test7 --chain-id localosmosis -b block`
8616754579BF5C5BC24141C7356FD1E5175126CEA615FAF012E4F9AA826FD160


Single asset LP OSMO to pool1 (test8)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uosmo 10000000 --pool-id 1 --from test8 --chain-id localosmosis -b block`
0F03A5161F48A46F8FC6C1DB89356225951A2838548DD98C7EBBBE3C8C37895B


Single asset LP ION to pool2 (test9)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uion 10000000 --pool-id 2 --from test9 --chain-id localosmosis -b block`
9B08A93A709E0DEAA53A57989746C862B1DB27BCAECA75A3B2F22207CA20AF37


Single asset LP OSMO to pool2 (test10)
`osmosisd tx gamm join-swap-extern-amount-in 10000000uosmo 10000000 --pool-id 2 --from test10 --chain-id localosmosis -b block`
F9FD6FFB2BC913572FB22BD21B91743C751AC2762CD7FD0D27C65D1A402A16FA


Exit 50 percent of initial from pool1 (test2)
`osmosisd tx gamm exit-pool --from test2 --share-amount-in 50000000000000000000 -b block --pool-id 1 --min-amounts-out=20000000uion --min-amounts-out=20000000uosmo --chain-id localosmosis`
A1EADDAD419B4452D128F796E31DE09266D72C81AD33ABC610C04DECF12C27D0


Exit 50 percent of initial from pool2 (test3)
`osmosisd tx gamm exit-pool --from test3 --share-amount-in 50000000000000000000 -b block --pool-id 2 --min-amounts-out=25000000uion --min-amounts-out=15000000uosmo --chain-id localosmosis`

AF6C8A2757D01139F7A6C14B74ABFC1B8E5017E188973431057385689177A635

Query all pools again

`osmosisd q gamm pools`
```
pools:
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1mw0ac6rwlp5r8wapwk3zs6g29h8fcscxqakdzw9emkne6c8wjp9q0t3v8t
  future_pool_governor: ""
  id: "1"
  poolAssets:
  - token:
      amount: "35229358"
      denom: uion
    weight: "5368709120"
  - token:
      amount: "35229358"
      denom: uosmo
    weight: "5368709120"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69900000000000000161"
    denom: gamm/pool/1
  totalWeight: "10737418240"
- '@type': /osmosis.gamm.v1beta1.Pool
  address: osmo1500hy75krs9e8t50aav6fahk8sxhajn9ctp40qwvvn8tcprkk6wszun4a5
  future_pool_governor: ""
  id: "2"
  poolAssets:
  - token:
      amount: "41084635"
      denom: uion
    weight: "6442450944"
  - token:
      amount: "29346168"
      denom: uosmo
    weight: "4294967296"
  poolParams:
    exitFee: "0.010000000000000000"
    smoothWeightChangeParams: null
    swapFee: "0.010000000000000000"
  totalShares:
    amount: "69832480157406130640"
    denom: gamm/pool/2
  totalWeight: "10737418240"
```
