### DISCUSSION TITLE
V11 Manual Gauge Fee And Gov Prop Testing

### DISCUSSION THREAD

**Discussion by czarcas7ic** [osmosis-labs/osmosis#2238] [General]
Need to first create a osmo/ion pool

```
{
    "weights": "5uion,5uosmo",
    "initial-deposit": "50000000uion,50000000uosmo",
    "swap-fee": "0.01",
    "exit-fee": "0.01",
    "future-governor": ""
}
```

`osmosisd tx gamm create-pool --from test2 --pool-file pool.json -b block --chain-id localosmosis`
30B28097CEDDC4AC0D8564120B56FCE8927DE8905ECCC85420643D9A1BD91C7E

We must now check if the wallet contains gamm/pool/1

`osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv`

```
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99950000000"
  denom: uion
- amount: "98950000000"
  denom: uosmo
```
gamm/pool/1 now exists

We now need to see if this created the respective gauges via the module account

`osmosisd q incentives gauges`

```
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "1"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-07-26T17:04:15.798169543Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 180s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "2"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-07-26T17:04:15.798169543Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 240s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "3"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-07-26T17:04:15.798169543Z"
```

It did!

Lets now create a gauge with test2 wallet for one of the lockable durations.

`osmosisd tx incentives create-gauge gamm/pool/1 10000000uion -b block --from test2 --epochs 10 --duration 120s --chain-id localosmosis`
A23551407079FF842C17E5A207526F3255B692289223972346D1B73BF8F70B15

I tried to do this with a non lockable duration and it did not work as expected (i.e. 24h in localosmosis is not a lockable duration).

Querying the bank balances again we should see a reduction of 10000000uion for the gauge itself and 50000000uosmo for the gauge creation fee

`osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv`

```
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99940000000"
  denom: uion
- amount: "98900000000"
  denom: uosmo
```

This is the case. Lets now check if the gauge was created properly

`osmosisd q incentives gauge-by-id 4`

```
gauge:
  coins:
  - amount: "10000000"
    denom: uion
  distribute_to:
    denom: gamm/pool/1
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "1970-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "4"
  is_perpetual: false
  num_epochs_paid_over: "10"
  start_time: "1970-01-01T00:00:00Z"
```

It was.

Now we test add to gauge

`osmosisd tx incentives add-to-gauge 4 10000000uion -b block --from test2 --epochs 5 --duration 120s --chain-id localosmosis`
9139D813FBF471D5C8B975C40EAFFA92E87A21B0BD551D71173278CE7B048037

Check if it was added properly

`osmosisd q incentives gauge-by-id 4`
```
gauge:
  coins:
  - amount: "20000000"
    denom: uion
  distribute_to:
    denom: gamm/pool/1
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "1970-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "4"
  is_perpetual: false
```

Check balance dif

`osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv`

```
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99930000000"
  denom: uion
- amount: "98875000000"
  denom: uosmo
```

**Comment by czarcas7ic** [comment]
When running `osmosisd q gov params` I saw that the min initial deposit ratio defaulted to 0 so I manually set it to 25%

Lets now try to submit a prop with no deposit

`osmosisd tx gov submit-proposal set-superfluid-assets-proposal --superfluid-assets gamm/pool/1 --from test2 -b block --title "sfs" --description "gamm/pool/1" --chain-id localosmosis`

Got the following error as expected:
`raw_log: 'failed to execute message; message index: 0: was (), need (2500000uosmo):
  minimum deposit is too small'`

Lets try with a deposit that is too small:

`osmosisd tx gov submit-proposal set-superfluid-assets-proposal --superfluid-assets gamm/pool/1 --from test2 -b block --title "sfs" --description "gamm/pool/1" --chain-id localosmosis --deposit 1000000uosmo`

Same, error as expected:
`raw_log: 'failed to execute message; message index: 0: was (1000000uosmo), need (2500000uosmo):
  minimum deposit is too small'`

Lets try just enough deposit:

`osmosisd tx gov submit-proposal set-superfluid-assets-proposal --superfluid-assets gamm/pool/1 --from test2 -b block --title "sfs" --description "gamm/pool/1" --chain-id localosmosis --deposit 2500000uosmo`

`osmosisd q gov proposals`

It works!

I realized I want to also check what happens to the deposit if it gets past the deposit period without getting enough deposits, so need to manually change genesis again

Set deposit period to 10 seconds, trying again

Query test2 balance pre deposit:

```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99950000000"
  denom: uion
- amount: "98950000000"
  denom: uosmo
```

After prop submit with 2500000uosmo

```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99950000000"
  denom: uion
- amount: "98947500000"
  denom: uosmo
```

After 10s deposit period, prop no longer displays, lets check wallet to make sure funds are gone

```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "99950000000"
  denom: uion
- amount: "98947500000"
  denom: uosmo
```

They are!
