### DISCUSSION TITLE
V11 Manual Test Remove Superfluid Asset

### DISCUSSION THREAD

**Discussion by czarcas7ic** [osmosis-labs/osmosis#2499] [General]
Create Pool
`osmosisd tx gamm create-pool --from test2 --pool-file pool.json -b block --chain-id localosmosis`

Add superfluid asset
`osmosisd tx gov submit-proposal set-superfluid-assets-proposal --from test2 --superfluid-assets gamm/pool/1 -b block --deposit 125000000uosmo --title "add sf asset" --description "add gamm/pool/1 sf" --chain-id localosmosis`
`osmosisd tx gov vote 2 yes --from val --yes -b block --chain-id localosmosis`
`osmosisd q gov proposal 2`

Check balances
```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "100000000000000000000"
  denom: gamm/pool/2
- amount: "100000000000000000000"
  denom: gamm/pool/3
- amount: "99850000000"
  denom: uion
- amount: "96725000000"
  denom: uosmo
```

SF stake to validator
osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6
`osmosisd tx lockup lock-tokens 100000000000000000000gamm/pool/1 --from test2 --duration 240s -b block --chain-id localosmosis`
`osmosisd tx superfluid lock-and-superfluid-delegate 100000000000000000000gamm/pool/1 osmovaloper1phaxpevm5wecex2jyaqty2a4v02qj7qm9v24r6 --from test2 -b block --yes --chain-id localosmosis`

Show asset multiplier
`osmosisd q superfluid asset-multiplier gamm/pool/1`
```
osmo_equivalent_multiplier:
  denom: gamm/pool/1
  epoch_number: "1"
  multiplier: "0.000000000000500000"
```

Remove sf asset
`osmosisd tx gov submit-proposal remove-superfluid-assets-proposal --from test2 --superfluid-assets gamm/pool/1 -b block --deposit 100000000uosmo --title "remove sf asset" --description "remove gamm/pool/1 sf" --chain-id localosmosis`
`osmosisd tx gov vote 3 yes --from val --yes -b block --chain-id localosmosis`

Check asset multiplier went to 0
```
czar@Adams-MacBook-Pro ~ % osmosisd q superfluid asset-multiplier gamm/pool/1
osmo_equivalent_multiplier:
  denom: gamm/pool/1
  epoch_number: "1"
  multiplier: "0.000000000000000000"
```
Current epoch 27
Wait a few epochs to ensure multiplier stays at 0
Now epoch 29
```
czar@Adams-MacBook-Pro ~ % osmosisd q superfluid asset-multiplier gamm/pool/1
osmo_equivalent_multiplier:
  denom: gamm/pool/1
  epoch_number: "1"
  multiplier: "0.000000000000000000"
```

Try and superfluid undelegate that was previously delegated
```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/2
- amount: "100000000000000000000"
  denom: gamm/pool/3
- amount: "99850000000"
  denom: uion
- amount: "96725000000"
  denom: uosmo
```
`osmosisd tx superfluid undelegate 1 --from test2 -b block --yes --chain-id localosmosis`
`osmosisd tx superfluid unbond-lock 1 --from test2 -b block --yes --chain-id localosmosis`
Wait for unbonding
```
czar@Adams-MacBook-Pro ~ % osmosisd q bank balances osmo18s5lynnmx37hq4wlrw9gdn68sg2uxp5rgk26vv
balances:
- amount: "100000000000000000000"
  denom: gamm/pool/1
- amount: "100000000000000000000"
  denom: gamm/pool/2
- amount: "100000000000000000000"
  denom: gamm/pool/3
- amount: "99850000000"
  denom: uion
- amount: "96725000000"
  denom: uosmo
```

Confirmed that:
- No panics
- People can still un-superfluid delegate
- Multiplier stays at 0 with successive epochs
