### DISCUSSION TITLE
Superfluid multi-node testing issue tracker

### DISCUSSION THREAD

**Discussion by mattverse** [osmosis-labs/osmosis#888] [General]
This issue is to track and confirm things are happening the way they should. Issues mentioned within this issue are from mulit-node environment. (Note that I might simply lack understanding and noting these out)

Also, instructions to the same setup is running `./multinode-local-testnet.sh`on a blank node, and runnning the following commands for basic superfluid set-up 
```
touch stake-uosmo.json
nano stake-uosmo.json 
`
{
	"weights": "5stake,5uosmo",
	"initial-deposit": "1000000stake,1000000uosmo",
	"swap-fee": "0.01",
	"exit-fee": "0.01",
	"future-governor": "168h"
}
`

# testing with validator1
# create pool
osmosisd tx gamm create-pool --pool-file=./stake-uosmo.json --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1

# test swap in pool created
osmosisd tx gamm swap-exact-amount-in 100000uosmo 50000 --swap-route-pool-ids=1 --swap-route-denoms=stake --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
osmosisd query gamm pool 1
osmosisd query bank balances $(osmosisd keys show -a validator1 --keyring-backend=test --home=$HOME/.osmosisd/validator1) --home=$HOME/.osmosisd/validator1

# create a lock up with lockable duration 2 min 
osmosisd tx lockup lock-tokens 10000000000000000000gamm/pool/1 --duration=360h --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1
osmosisd query lockup lock-by-id 1 --home=$HOME/.osmosisd/validator1
osmosisd query staking validators --home=$HOME/.osmosisd/validator1

# submit a gov proposal to set superfluid asset, deposit and pass proposal
osmosisd tx gov submit-proposal set-superfluid-assets-proposal --title="set superfluid assets" --description="set superfluid assets description" --superfluid-assets="gamm/pool/1" --deposit=10000000uosmo --from=validator1 --chain-id=testing --keyring-backend=test --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1
osmosisd tx gov deposit 1 10000000stake --from=validator1 --keyring-backend=test --chain-id=testing --broadcast-mode=block --yes --home=$HOME/.osmosisd/validator1
osmosisd tx gov vote 1 yes --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
osmosisd tx gov vote 1 yes --from=validator2 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator2
# query if superfluid asset exists
osmosisd query superfluid asset-multiplier gamm/pool/1 --home=$HOME/.osmosisd/validator1
# query intermediary accounts, should not have any intermediary accounts yet
osmosisd query superfluid all-intermediary-accounts --home=$HOME/.osmosisd/validator1


# get any of the val addresses to use for superfluid staking
osmosisd query staking validators --home=$HOME/.osmosisd/validator1

# superfluid delegate
osmosisd tx superfluid delegate 1 osmovaloper1vh2sdnecklyw3ksxusy7e3hgrk73cw5xqh9gzm --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
```

**Comment by mattverse** [comment]
### Address returns from non-existent connected-intermediary-account 

Without anyone superfluid staked, `osmosisd query superfluid connected-intermediary-account **any_int**` returns an address. From my understanding, [test code](https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/intermediary_account_test.go#L44-L49) indicates that it shouldn't return an address but rather an empty address. 

Log
```
# we have gamm/pool/1 registered as superfluid asset
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-superfluid-assets
assets:
- asset_type: SuperfluidAssetTypeLPShare
  denom: gamm/pool/1

# this shows that noone has superfluid-staked before
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-intermediary-accounts
accounts: []
pagination: null

# the part I don't understand. Querying returns a result with a address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""

# lock seven does not exist but still returns an address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 7 --home=$HOME/.osmosisd/validator1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""
```

**Comment by mattverse** [comment]
### Superfluid delegation rewards not being moved to gauges nor being auto distributed to delegators


From my understanding, every epoch that's ending should be calling `MoveSuperfluidDelegationRewardToGauges`, which is supposed to withdraw delegation rewards and add them to gauges which then gets auto-distributed to the delegators every epoch. The problem situation is that I'm not getting the rewards automatically from suerfluid staking.

Noting some of the genesis configuration that's related to epoch and distribution: `incentvies.params.distr_epcoh_identifier= min`, `mint.params.epoch_identifier = min`, `superfluid.params.refresh_epoch_identifier=min`


 Log: 
```
# check balances
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd query bank balances $(osmosisd keys show -a validator1 --keyring-backend=test --home=$HOME/.osmosisd/validator1) --home=$HOME/.osmosisd/validator1
balances:
- amount: "4000000000"
  denom: stake
- amount: "3600000000"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
 
# check time
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# date
Tue Feb 15 23:40:53 UTC 2022
  
# more than a minute(epoch time) has passed
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# date
Tue Feb 15 23:44:34 UTC 2022

# balances are still the same
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd query bank balances $(osmosisd keys show -a validator1 --keyring-backend=test --home=$HOME/.osmosisd/validator1) --home=$HOME/.osmosisd/validator1
balances:
- amount: "4000000000"
  denom: stake
- amount: "3600000000"
  denom: uosmo
pagination:
  next_key: null
  
# nothing in the gauges as well 
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd q incentives gauges
data:
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "67"
  id: "1"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 180s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "2"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 240s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "3"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1superbondingosmovaloper1783a9rwv89p9lt4tywm2rswu7lvc9zzgj8wl55
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "63"
  id: "4"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:40:26.400490447Z"

```

**Reply by mattverse** [reply]
Confirmed that this was happening, fix in: https://github.com/osmosis-labs/osmosis/pull/894

**Reply by ValarDragon** [reply]
OH wait the rewards not getting into gauges I did not know. That is a problem I haven't looked into, ty!

**Reply by czarcas7ic** [reply]
I am now getting rewards automatically, the fix in #894 was likely the cause

**Comment by daniel-farina** [comment]
@mattverse 
What branch are we using to the perform the testing above?

**Comment by daniel-farina** [comment]


**Reply by czarcas7ic** [reply]
You probably just need to add a --fees flag, i will take a look

**Reply by ValarDragon** [reply]
hrmm, 0 fee should work. I think its possible something in the SDK may have broken if this is the case

**Reply by ValarDragon** [reply]
Can we double check if this PR is new to where we were on v44 and are now in v45? 

https://github.com/cosmos/cosmos-sdk/pull/10327/files

Maybe we have to change something in the SDK if so?

**Reply by czarcas7ic** [reply]
I was unable to replicate this nor was Matt

**Comment by czarcas7ic** [comment]
@mattverse I was able to replicate everything from the original instructions. Something odd I ran into (could be normal behavior but doesn't seem right to me):

Superfluid staked to validator 3 (weakest validator) on block 273, saw its tokens/delegator shares increase after superfluid stake that same block. On block 282, token amount went back to original amount pre superfluid delegation. Is this normal behavior? I was going to test what would happen if I superfluid staked enough to make validator 3 strong enough to where if I were to shut off either validator 1 or validator 2, whether the network would continue to run or not (to see if superfluid power acted normally to allow the network to run off 66% power created by superfluid stake), but came across the tokens disappearing after a few blocks. 

Block of superfluid stake (height 273, tokens/delegator shares 400104500):
<img width="1369" alt="Screen Shot 2022-02-19 at 10 32 39 AM" src="https://user-images.githubusercontent.com/40078083/154810040-d467391c-d910-4033-8635-6026978519af.png">

9 blocks later (height 282, tokens/delegator shares 400000000):
<img width="1325" alt="Screen Shot 2022-02-19 at 10 39 01 AM" src="https://user-images.githubusercontent.com/40078083/154810053-f38d5dbf-13bb-4dac-9dd7-fb1cd4ff1716.png">

Superfluid delegation still shows when querying all-intermediary-accounts.

Tried testing this again and similar result

Block of superfluid stake (height 580, tokens/delegator shares 400940500):
<img width="1369" alt="Screen Shot 2022-02-19 at 10 50 11 AM" src="https://user-images.githubusercontent.com/40078083/154810451-1566bca4-570b-42c9-9f48-89a959d74155.png">

3 blocks later (height 583, tokens/delegator shares 400000000)
<img width="1325" alt="Screen Shot 2022-02-19 at 10 50 35 AM" src="https://user-images.githubusercontent.com/40078083/154810472-6da37391-364e-4c5b-9917-60334b6f3b22.png">

**Reply by czarcas7ic** [reply]
This is now fixed

**Comment by czarcas7ic** [comment]
As it stands, an epoch must pass before the osmo equivalency is updated. This means that without modification, no one will be able to superfluid delegate until the epoch after the superfluid asset is approved via governance. 

![Screen Shot 2022-02-21 at 12 24 55 AM](https://user-images.githubusercontent.com/40078083/154906679-170a36c8-92c6-4b46-afe6-9f0e9bc4c17e.png)

**Reply by czarcas7ic** [reply]
Fixed by @mattverse on this branch mattverse/superfluid-gov-fix

**Comment by czarcas7ic** [comment]
Not an issue, but wanted to show this was tested

Changed the max validator set to 2, then superfluid delegated to an unbonded validator, and the corresponding power pushed it into the validator set as expected

**Comment by czarcas7ic** [comment]
Got superfluid payout on the first epoch after the first superfluid stake:

Height 3719 (epoch 334)
```
root@adam-frontend-test:~# osmosisd tx superfluid delegate 2 osmovaloper1jc0n6umjpcn30aajlxwr6v399y5pdf9ucsm3ap --from=validator1 --keyring-backend=test --chain-id=testing --yes --home=$HOME/.osmosisd/validator1
```
Height 3734 (epoch 335)
```
root@adam-frontend-test:~# osmosisd q epochs epoch-infos --height 3734
epochs:
- current_epoch: "335"
  current_epoch_start_height: "3724"
  current_epoch_start_time: "2022-02-23T23:40:05.876450934Z"
  duration: 60s
  epoch_counting_started: true
  identifier: day
  start_time: "2022-02-23T18:06:05.876450934Z"
- current_epoch: "1"
  current_epoch_start_height: "1"
  current_epoch_start_time: "2022-02-23T18:06:05.876450934Z"
  duration: 604800s
  epoch_counting_started: true
  identifier: week
  start_time: "2022-02-23T18:06:05.876450934Z"
root@adam-frontend-test:~# osmosisd q bank balances osmo16wthxdpg6nf6l48t76hka4446v5dmhm2wruuyr --height 3720
balances:
- amount: "90000000000000000000"
  denom: gamm/pool/1
- amount: "100000000000000000000"
  denom: gamm/pool/2
- amount: "99890196931"
  denom: stake
- amount: "96489800000"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
root@adam-frontend-test:~# osmosisd q bank balances osmo16wthxdpg6nf6l48t76hka4446v5dmhm2wruuyr --height 3734
balances:
- amount: "90000000000000000000"
  denom: gamm/pool/1
- amount: "100000000000000000000"
  denom: gamm/pool/2
- amount: "99890196931"
  denom: stake
- amount: "96489800150"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
```
