### ISSUE TITLE
CI: Make PRs not run tests twice on each commit

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis#1100]
Right now CI runs tests twice for every commit on a PR. One for (push) and one for (pull request). We actually often get into a situation where the push test is done, but we're still waiting on the pull request CI test.

Is it possible to de-duplicate this? Perhaps only having tests on commit? (Do we lose anything by doing that?)

**Comment by nikever** [comment]
As you said we run the `test` workflow on any push to any branch and any pull_request event: 

```yaml

# Event that triggers the workflow
on:
  pull_request:           # any pull_request event:
  push:                   # any push to any branch 
    branches:
      - '**'	
```

Possible solutions to avoid duplicated runs are:

1) Don't run  the workflow on `pull_request` event:

```yaml
on:
  push:
    branches:
      - '**'	
```

This is super simple to do but doing so we lose the codecov report comment on PRs as in  https://github.com/osmosis-labs/osmosis/pull/1098#issuecomment-1067954796. 
I think that the report would still will be accessible inspecting the workflow run.

2) A more complicated solution to avoid running both on `push` and on `pull_request` would be to add a check before running the job using https://github.com/fkirc/skip-duplicate-actions. 
It would complicate a little bit the workflow and might need some tweaking to find the right configuration but it's doable. More info: https://github.com/fkirc/skip-duplicate-actions#example-1-skip-entire-jobs

----

If we don't care much about the codecov report on the comment I would go with `1` which is super simple to do. Otherwise I'll start to play around with https://github.com/fkirc/skip-duplicate-actions.

What do you think?
