### ISSUE TITLE
REST query for total_liquidity returns an error

### ISSUE THREAD

**Issue by dogemos** [osmosis-labs/osmosis#246]
Querying the gamm/total_liquidity through REST endpoint returns the following message:
```
{
  "code": 3,
  "message": "type mismatch, parameter: poolId, error: strconv.ParseUint: parsing \"total_liquidity\": invalid syntax",
  "details": []
}
```

However, querying the total_liquidity through the CLI returns a normal response:
```
liquidity:
- amount: "9998121"
  denom: ion
- amount: "500105"
  denom: uosmo
```
