### ISSUE TITLE
chore: enable linting on go tests

### ISSUE THREAD

**Issue by faddat** [osmosis-labs/osmosis#3695]
So, when I was working on the ibc-go upgrade to v0.47.x, I noticed something:

```yaml
run:
  tests: false
  timeout: 5m

linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  enable:
    - asciicheck
    - bidichk
    - depguard
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - forcetypeassert
    - goconst
    - gofumpt
    - goheader
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilnil
    - paralleltest
    - promlinter
    - staticcheck
    - stylecheck
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: x/gamm/pool-models/stableswap
      linters:
        # Stableswap is in development.
        # We should re-enable deadcode and unused linting
        # across its files, once stableswap is fully complete.
        - unused
        - deadcode
    - linters:
        - staticcheck
      text: "SA1024: cutset contains duplicate characters" # proved to not provide much value, only false positives.
    - linters:
        - staticcheck
      text: "SA9004: only the first constant in this group has an explicit type" # explicitly recommended in go syntax
    - linters:
        - stylecheck
      text: "ST1003:" # requires identifiers with "id" to be "ID".
    - linters:
        - stylecheck
      text: "ST1005:" # punctuation in error messages
  max-issues-per-linter: 10000
  max-same-issues: 10000
```

See how tests are set to false?  This meant that in the cosmos-sdk and ibc-go, tests weren't being linted. 

So basically, I'm proposing that I make another PR like #3486 and that will change `tests: false` to `tests:true`.

Then we can change the Makefile, so that the only thing we do for both formatting and linting is:

```bash
golangci-run ./... --fix
```
