### ISSUE TITLE
[CL]: Investigate CalcActualAmounts rounding behavior

### ISSUE THREAD

**Issue by czarcas7ic** [osmosis-labs/osmosis#4644]
## Background

When utilizing the CalcActualAmounts function in the user positions query, Roman noticed odd rounding behavior in the result. For instance:

```
positions:
- asset0: "5000000000.000000000000000000"
  asset1: "999999.929289321953752005"
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    freeze_duration: 0s
    join_time: "2023-03-15T23:34:18.294912471Z"
    liquidity: "70710678.118654755000100000"
    lower_tick: "-1620000"
    pool_id: "4"
    upper_tick: "3420000"
- asset0: "5000000000.000000000000052404"
  asset1: "0.000000000000000000"
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    freeze_duration: 0s
    join_time: "2023-03-15T23:34:33.429215298Z"
    liquidity: "2997892628892.147707843478961141"
    lower_tick: "300000"
    pool_id: "4"
    upper_tick: "309990"
- asset0: "4999999999.999999999999945060"
  asset1: "0.000000000000000000"
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    freeze_duration: 0s
    join_time: "2023-03-15T23:34:23.335370459Z"
    liquidity: "3706060757243.600559263910088981"
    lower_tick: "305450"
    pool_id: "4"
    upper_tick: "315000"
- asset0: "5000000000.000000000000067028"
  asset1: "0.000000000000000000"
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    freeze_duration: 0s
    join_time: "2023-03-15T23:34:28.384895378Z"
    liquidity: "5988837224777.540616115005684301"
    lower_tick: "315000"
    pool_id: "4"
    upper_tick: "322500"
```

If you look at positions 2-4, you will see trailing digits after 5000000000. The problem is, the user only input a maximum of 5000000000, so the number should be 5000000000 or lower.

## Suggested Design

TBD

## Acceptance Criteria

Rounding behavior investigated and an explanation for this is given.

Rounding behavior should always round in favor of the protocol.

**Comment by stackman27** [comment]
updated user-positions query. Seems like the issue has been resolve as we truncate amount
cc @czarcas7ic @p0mvn 
```
positions:
- asset0:
    amount: "5000000000"
    denom: uosmo
  asset1:
    amount: "999999"
    denom: uion
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    join_time: "2023-04-13T00:45:37.660871291Z"
    liquidity: "70710678.118654755000100000"
    lower_tick: "-1620000"
    pool_id: "4"
    position_id: "1"
    upper_tick: "3420000"
- asset0:
    amount: "4999999999"
    denom: uosmo
  asset1:
    amount: "0"
    denom: uion
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    join_time: "2023-04-13T00:45:42.710505605Z"
    liquidity: "3706060757243.600559263910088981"
    lower_tick: "305450"
    pool_id: "4"
    position_id: "2"
    upper_tick: "315000"
- asset0:
    amount: "5000000000"
    denom: uosmo
  asset1:
    amount: "0"
    denom: uion
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    join_time: "2023-04-13T00:45:47.755816844Z"
    liquidity: "5988837224777.540616115005684301"
    lower_tick: "315000"
    pool_id: "4"
    position_id: "3"
    upper_tick: "322500"
- asset0:
    amount: "5000000000"
    denom: uosmo
  asset1:
    amount: "0"
    denom: uion
  position:
    address: osmo1jllfytsz4dryxhz5tl7u73v29exsf80vz52ucc
    join_time: "2023-04-13T00:45:52.799517929Z"
    liquidity: "2997892628892.147707843478961141"
    lower_tick: "300000"
    pool_id: "4"
    position_id: "4"
    upper_tick: "309990"
```
