### ISSUE TITLE
fix(CL): broken CLI queries

### ISSUE THREAD

**Issue by p0mvn** [osmosis-labs/osmosis#4909]
## Background

```bash
osmosisd q concentratedliquidity pools
Error: proto: wrong wireType = 2 for field Id
osmosisd q concentratedliquidity pool 1
Error: rpc error: code = Unknown desc = unknown query path: unknown request
```

## Acceptance Criteria
- fixed
- tested on localosmosis

**Comment by stackman27** [comment]
currently working on my end 
```
❯ osmosisd q concentratedliquidity pools
pagination:
  next_key: null
  total: "0"
pools:
- '@type': /osmosis.concentratedliquidity.v1beta1.Pool
  address: osmo1ad4r3uh5pdn5pgg5hnl6u5utfeqmpwstlvgvg2h2jdztrcnwkqgs3hs85z
  current_sqrt_price: "0.014142135623730951"
  current_tick: "-350000"
  current_tick_liquidity: "70710678.118654755000100000"
  exponent_at_price_one: "-4"
  id: "4"
  incentives_address: osmo1ra25mx8lch089mxf97nr6cnzns7vesecvw0mxj32fcaj5ygrsd8sqwhjpk
  last_liquidity_update: "2023-04-14T03:31:51.593814278Z"
  swap_fee: "0.010000000000000000"
  tick_spacing: "1"
  token0: uosmo
  token1: uion
```
