### ISSUE TITLE
About `rest-api` query not getting correct results.

### ISSUE THREAD

**Issue by 99Kies** [osmosis-labs/osmosis#6025]
network: `osmosis-testnet-5`

I'm trying to get the latest validator, proposal and staking related data based on the rest api, but every request is so slow that I can't even request the data.

I want to build a full node to provide efficient rest service by myself, what should I do.

![image](https://github.com/osmosis-labs/osmosis/assets/45918704/1ecf4e4b-cbf7-4f6f-aea4-ebbd240ef571)

It shows on mintscan that this person has made a vote, but the rest service provided by the full node I've built queries quite a bit of this person's vote information.

![image](https://github.com/osmosis-labs/osmosis/assets/45918704/f38e4057-73cc-4bbf-8683-c17722e10a38)

and https://lcd.osmotest5.osmosis.zone/swagger/#/Query/Vote also failed.

![image](https://github.com/osmosis-labs/osmosis/assets/45918704/dca92206-d716-472c-bbe3-4176b29c9e79)

`app.toml`:

```toml
[api]

# Enable defines if the API server should be enabled.
enable = true

# Swagger defines if swagger documentation should automatically be registered.
swagger = false

# Address defines the API server to listen on.
address = "tcp://0.0.0.0:1317"

# MaxOpenConnections defines the number of maximum open connections.
max-open-connections = 1000

# RPCReadTimeout defines the Tendermint RPC read timeout (in seconds).
rpc-read-timeout = 10

# RPCWriteTimeout defines the Tendermint RPC write timeout (in seconds).
rpc-write-timeout = 0

# RPCMaxBodyBytes defines the Tendermint maximum response body (in bytes).
rpc-max-body-bytes = 1000000

# EnableUnsafeCORS defines if CORS should be enabled (unsafe - use it at your own risk).
enabled-unsafe-cors = false
```
