### ISSUE TITLE
[Bug]: pool creation denom is not required to be existing denom

### ISSUE THREAD

**Issue by doggystylez** [osmosis-labs/osmosis#6883]
### What happened?

a cl pool can be created with any string that can be validated as denom, whether or not it exists on chain 
see:
```
osmosisd q poolmanager pool 1272
pool:
  '@type': /osmosis.concentratedliquidity.v1beta1.Pool
  address: osmo17a7ujdgqcq5j0pnluu5k9a62gn92lll90scz8tc8xz2sz2wwnrjqtvq2d7
  current_sqrt_price: "0.000000000000000000000000000000000000"
  current_tick: "0"
  current_tick_liquidity: "0.000000000000000000"
  exponent_at_price_one: "-6"
  id: "1272"
  incentives_address: osmo1ydyqnx4rmpqklycaznxasdg5885u6hs3tpscchnypl4vplqs4rns8cm2lv
  last_liquidity_update: "2023-11-09T13:45:22.505190401Z"
  spread_factor: "0.005000000000000000"
  spread_rewards_address: osmo1sujy0nt2l4xjsjyrprl8uek95fuldz2m9dty2q950tg39ktre8rq89ze83
  tick_spacing: "100"
  token0: ncheq
  token1: ibc/498A0751C798A0D9A389AA3691123DADA57DAA4FE165D5C75894505B876BA6E4
```

### Osmosis Version

v20
