### ISSUE TITLE
[QUESTION] Could not create a position for a pool with 1:1 ratio when token0.decimals != token1.decimals

### ISSUE THREAD

**Issue by BoThe1K** [osmosis-labs/osmosis#8679]
Hi! I have used  instructions https://docs.osmosis.zone/overview/integrate/pool-setup#join-pool for pool creation and created a supercharged liquidity pool with Osmosis token (6 decimals) and my ibc token (18 decimals) for the full range (-108000000 : 342000000) for 1:1 price ( I have expected that it will be 1:1):

https://www.mintscan.io/osmosis/address/osmo1yfuqh7z885u4jaj7su4a7qdd7psn3a420jy835
```
pool-id: 2168
position-id: 8138960
```

But pool showing current_tick is -108000001 (expected to be 0 as I wanted to 1:1)
```
pool:
  '@type': /osmosis.concentratedliquidity.v1beta1.Pool
  address: osmo1tjjxzr4fwmqnwe4mlqz8q6pwu4kexzjftpgq0jnglazfdg2lj0fq64rvs2
  current_sqrt_price: "0.000001000000000000000000000000000000"
  current_tick: "-108000001"
  current_tick_liquidity: "0.000000000000000000"
  exponent_at_price_one: "-6"
  id: "2168"
  incentives_address: osmo16eym3u4h2hx4rqg0kgtfulyfl0a2ahg07jjvmkgcp3qf0yy497hsdh3rve
  last_liquidity_update: "2024-09-06T14:35:21.230983192Z"
  spread_factor: "0.001000000000000000"
  spread_rewards_address: osmo1em89gxdw97jwc03dh3grcws0dht3ev62phaq55n0fewnsw96a0xsmjlymm
  tick_spacing: "100"
  token0: ibc/ABD49F44559CB3E557CC458459CB6A67CEBD66E23C7674A0B2B445230BDA1F6C
  token1: uosmo
```

So how to make it 1:1 ratio if there is a difference of the decimals?
Is this related to a decimals and I could only use a IBC token with 6 decimals as uosmo?
