### ISSUE TITLE
Superfluid multi-node testing issue tracker

### ISSUE THREAD

**Issue by mattverse** [osmosis-labs/osmosis#874]
This issue is to track and confirm things for supposed to happen the way they should. Note that issues mentioned within this issue is omitted from mulit-node environment.

**Comment by mattverse** [comment]
### Address returns from non-existent connected-intermediary-account 

Without anyone superfluid staked, `osmosisd query superfluid connected-intermediary-account **any_int**` returns an address. From my understanding, [test code](https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/intermediary_account_test.go#L44-L49) indicates that it shouldn't return an address but rather an empty address. 

Log
```
# we have gamm/pool/1 registered as superfluid asset
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-superfluid-assets
assets:
- asset_type: SuperfluidAssetTypeLPShare
  denom: gamm/pool/1

# this shows that noone has superfluid-staked before
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-intermediary-accounts
accounts: []
pagination: null

# the part I don't understand. Querying returns a result with a address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""

# lock seven does not exist but still returns an address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 7 --home=$HOME/.osmosisd/validator1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""
```

**Comment by mattverse** [comment]
### Address returns from non-existent connected-intermediary-account 

Without anyone superfluid staked, `osmosisd query superfluid connected-intermediary-account **any_int**` returns an address. From my understanding, [test code](https://github.com/osmosis-labs/osmosis/blob/main/x/superfluid/keeper/intermediary_account_test.go#L44-L49) indicates that it shouldn't return an address but rather an empty address. 

Log
```
# we have gamm/pool/1 registered as superfluid asset
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-superfluid-assets
assets:
- asset_type: SuperfluidAssetTypeLPShare
  denom: gamm/pool/1

# this shows that noone has superfluid-staked before
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid all-intermediary-accounts
accounts: []
pagination: null

# the part I don't understand. Querying returns a result with a address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""

# lock seven does not exist but still returns an address
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/osmosis# osmosisd query superfluid connected-intermediary-account 7 --home=$HOME/.osmosisd/validator1
account:
  address: osmo1uwcvgs5clswpfxhm7nyfjmaeysn6us0ydmdj3a
  denom: ""
  gauge_id: "0"
  val_addr: ""
```

**Comment by mattverse** [comment]
### Superfluid delegation rewards not being moved to gauges nor being auto distributed to delegations

From my understanding, every epoch that's ending should be calling `MoveSuperfluidDelegationRewardToGauges`, which is supposed to withdraw delegation rewards and add them to gauges which then gets auto-distributed to the delegators every epoch. The problem situation is that I'm not getting the rewards automatically from suerfluid staking.

Noting some of the genesis configuration that's related to epoch and distribution: `incentvies.params.distr_epcoh_identifier= min`, `mint.params.epoch_identifier = min`, `superfluid.params.refresh_epoch_identifier=min`


 Log: 
```
# check balances
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd query bank balances $(osmosisd keys show -a validator1 --keyring-backend=test --home=$HOME/.osmosisd/validator1) --home=$HOME/.osmosisd/validator1
balances:
- amount: "4000000000"
  denom: stake
- amount: "3600000000"
  denom: uosmo
pagination:
  next_key: null
  total: "0"
 
# check time
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# date
Tue Feb 15 23:40:53 UTC 2022
  
# more than a minute(epoch time) has passed
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# date
Tue Feb 15 23:44:34 UTC 2022

# balances are still the same
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd query bank balances $(osmosisd keys show -a validator1 --keyring-backend=test --home=$HOME/.osmosisd/validator1) --home=$HOME/.osmosisd/validator1
balances:
- amount: "4000000000"
  denom: stake
- amount: "3600000000"
  denom: uosmo
pagination:
  next_key: null
  
# nothing in the gauges as well 
root@ubuntu-s-4vcpu-8gb-amd-sfo3-01:~/.osmosisd/validator1/config# osmosisd q incentives gauges
data:
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "67"
  id: "1"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 180s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "2"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1
    duration: 240s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "0"
  id: "3"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:35:48.077726119Z"
- coins: []
  distribute_to:
    denom: gamm/pool/1superbondingosmovaloper1783a9rwv89p9lt4tywm2rswu7lvc9zzgj8wl55
    duration: 120s
    lock_query_type: ByDuration
    timestamp: "0001-01-01T00:00:00Z"
  distributed_coins: []
  filled_epochs: "63"
  id: "4"
  is_perpetual: true
  num_epochs_paid_over: "1"
  start_time: "2022-02-15T22:40:26.400490447Z"

```
